### ISSUE TITLE
Change direction of UI blue arrows after clicking to expand quote

### ISSUE THREAD

**Issue by timlangeman** [CiteIt/citeit-wordpress#10]
- When a quote is expanded, the arrows do not toggle to indicate the quote can be compressed back to its prior position.  Change the arrow using the HTML arrow symbol and javascript.

**Comment by timlangeman** [comment]
Here's a sample of what the current blue arrows look like.  They should reverse after the quote has been expanded.

### Screenshot:
![sample-quote-arrows](https://user-images.githubusercontent.com/134813/69747264-0d659280-1114-11ea-8b1f-0427d74c579b.png)

**Comment by rajats98** [comment]
Is this issue still open
I want to work on this!

**Comment by timlangeman** [comment]
Yes, this issue is still open.  Go right ahead!
